### ISSUE TITLE
Crash on Usage

### ISSUE THREAD

**Issue by HiddenPug** [hashalite/Freecam#100]
Consistent crash after using Freecam. Version 1.2.0, all other mods/resource packs disabled

The game crashed whilst ticking entity
Error: java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;

---- Minecraft Crash Report ----
// I let you down. Sorry :(

Time: 7/12/23 10:27 AM
Description: Ticking entity

java.lang.NoSuchMethodError: java.util.List.of(Ljava/lang/Object;Ljava/lang/Object;Ljava/lang/Object;)Ljava/util/List;
	at net.xolt.freecam.config.CollisionWhitelist.<clinit>(CollisionWhitelist.java:10)
	at net.minecraft.class_4970$class_4971.handler$zhg000$freecam$onGetCollisionShape(class_4970.java:1077)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
	at net.minecraft.class_5329.method_29285(class_5329.java:97)
	at net.minecraft.class_5329.tryAdvance(class_5329.java:62)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at net.minecraft.class_1941.method_8590(class_1941.java:50)
	at net.minecraft.class_1941.method_8587(class_1941.java:46)
	at net.minecraft.class_1297.method_20233(class_1297.java:1840)
	at net.minecraft.class_1657.method_7318(class_1657.java:402)
	at net.minecraft.class_1657.method_5773(class_1657.java:321)
	at net.minecraft.class_746.method_5773(class_746.java:205)
	at net.minecraft.class_638.method_18646(class_638.java:193)
	at net.minecraft.class_638$$Lambda$5266/1917982358.accept(Unknown Source)
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_638.method_18116(class_638.java:164)
	at net.minecraft.class_310.method_1574(class_310.java:1556)
	at net.minecraft.class_310.method_1523(class_310.java:1021)
	at net.minecraft.class_310.method_1514(class_310.java:681)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.xolt.freecam.config.CollisionWhitelist.<clinit>(CollisionWhitelist.java:10)
	at net.minecraft.class_4970$class_4971.handler$zhg000$freecam$onGetCollisionShape(class_4970.java:1077)
	at net.minecraft.class_4970$class_4971.method_26194(class_4970.java)
	at net.minecraft.class_5329.method_29285(class_5329.java:97)
	at net.minecraft.class_5329.tryAdvance(class_5329.java:62)
	at java.util.stream.Streams$ConcatSpliterator.tryAdvance(Streams.java:728)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:529)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:516)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:502)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.allMatch(ReferencePipeline.java:454)
	at net.minecraft.class_1941.method_8590(class_1941.java:50)
	at net.minecraft.class_1941.method_8587(class_1941.java:46)
	at net.minecraft.class_1297.method_20233(class_1297.java:1840)
	at net.minecraft.class_1657.method_7318(class_1657.java:402)
	at net.minecraft.class_1657.method_5773(class_1657.java:321)
	at net.minecraft.class_746.method_5773(class_746.java:205)
	at net.minecraft.class_638.method_18646(class_638.java:193)
	at net.minecraft.class_638$$Lambda$5266/1917982358.accept(Unknown Source)

-- Entity being ticked --
Details:
	Entity Type: minecraft:player (net.xolt.freecam.util.FreeCamera)
	Entity ID: -420
	Entity Name: FreeCamera
	Entity's Exact location: -3217.69, 173.22, -3400.87
	Entity's Block location: World: (-3218,173,-3401), Chunk: (at 14,10,7 in -202,-213; contains blocks -3232,0,-3408 to -3217,255,-3393), Region: (-7,-7; contains chunks -224,-224 to -193,-193, blocks -3584,0,-3584 to -3073,255,-3073)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: ~~ERROR~~ NullPointerException: null
Stacktrace:
	at net.minecraft.class_1937.method_18472(class_1937.java:561)
	at net.minecraft.class_638.method_18116(class_638.java:164)

-- Affected level --
Details:
	All players: 1 total; [class_746['Mopcen'/155, l='ClientLevel', x=-3217.69, y=172.00, z=-3400.87]]
	Chunk stats: Client Chunk Cache: 1369, 961
	Level dimension: minecraft:the_nether
	Level spawn location: World: (160,66,-176), Chunk: (at 0,4,0 in 10,-11; contains blocks 160,0,-176 to 175,255,-161), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 30965 game time, 30965 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:449)
	at net.minecraft.class_310.method_1587(class_310.java:2239)
	at net.minecraft.class_310.method_1514(class_310.java:699)
	at net.minecraft.client.main.Main.main(Main.java:215)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_51, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 1110725168 bytes (1059 MB) / 3230138368 bytes (3080 MB) up to 7635730432 bytes (7282 MB)
	CPUs: 12
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8G -Xms256m
	Fabric Mods: 
		cloth-basic-math: cloth-basic-math 0.6.0
		cloth-config2: Cloth Config v4 4.14.54
		fabric: Fabric API 0.42.0+1.16
		fabric-api-base: Fabric API Base 0.4.0+3cc0f0907d
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.3.1+3cc0f0907d
		fabric-biome-api-v1: Fabric Biome API (v1) 3.1.13+3cc0f0907d
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.6+3cc0f0907d
		fabric-command-api-v1: Fabric Command API (v1) 1.1.3+3cc0f0907d
		fabric-commands-v0: Fabric Commands (v0) 0.2.3+3cc0f0907d
		fabric-containers-v0: Fabric Containers (v0) 0.1.12+3cc0f0907d
		fabric-content-registries-v0: Fabric Content Registries (v0) 0.2.5+3cc0f0907d
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.4+3cc0f0907d
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.0.8+3cc0f0907d
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.2.4+3cc0f0907d
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.5+3cc0f0907d
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.2+3cc0f0907d
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.7+3cc0f0907d
		fabric-item-api-v1: Fabric Item API (v1) 1.2.2+3cc0f0907d
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.1+3cc0f0907d
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.5+3cc0f0907d
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.2+3cc0f0907d
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 1.2.2+3cc0f0907d
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.3+3cc0f0907d
		fabric-mining-levels-v0: Fabric Mining Levels (v0) 0.1.4+3cc0f0907d
		fabric-models-v0: Fabric Models (v0) 0.3.1+3cc0f0907d
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.5+3cc0f0907d
		fabric-networking-blockentity-v0: Fabric Networking Block Entity (v0) 0.2.9+3cc0f0907d
		fabric-networking-v0: Fabric Networking (v0) 0.3.3+3cc0f0907d
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 1.9.6+3cc0f0907d
		fabric-object-builders-v0: Fabric Object Builders (v0) 0.7.3+3cc0f0907d
		fabric-particles-v1: Fabric Particles (v1) 0.2.5+3cc0f0907d
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.7.6+3cc0f0907d
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.5+3cc0f0907d
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.4.5+3cc0f0907d
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 2.3.1+3cc0f0907d
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.1.6+3cc0f0907d
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 0.1.15+3cc0f0907d
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.3+3cc0f0907d
		fabric-rendering-v1: Fabric Rendering (v1) 1.6.1+3cc0f0907d
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.8+3cc0f0907d
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.1+3cc0f0907d
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.1.6+3cc0f0907d
		fabric-structure-api-v1: Fabric Structure API (v1) 1.1.12+3cc0f0907d
		fabric-tag-extensions-v0: Fabric Tag Extensions (v0) 1.1.2+3cc0f0907d
		fabric-textures-v0: Fabric Textures (v0) 1.0.7+3cc0f0907d
		fabric-tool-attribute-api-v1: Fabric Tool Attribute API (v1) 1.2.8+3cc0f0907d
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.5.0+3cc0f0907d
		fabricloader: Fabric Loader 0.14.21
		freecam: Freecam 1.2.0+1.16
		java: Java HotSpot(TM) 64-Bit Server VM 8
		minecraft: Minecraft 1.16.5

**Comment by hashalite** [comment]
Thanks for reporting, this will be fixed in the next update.

**Comment by hashalite** [comment]
@HiddenPug Fixed in 1.2.1
