### ISSUE TITLE
1.20.2

### ISSUE THREAD

**Issue by MetalFrog** [hashalite/Freecam#107]
Pressing my keybind to enter freecam mode crashes the game on 1.20.2. I'm assuming it's an issue because I'm trying to use it on the latest version with the updated Fabric Loader/API, and probably not a bug. 

```
[18:59:46] [Render thread/ERROR]: Unreported exception thrown!
java.lang.NoSuchMethodError: 'void net.minecraft.class_634.<init>(net.minecraft.class_310, net.minecraft.class_437, net.minecraft.class_2535, net.minecraft.class_642, com.mojang.authlib.GameProfile, net.minecraft.class_7975)'
	at net.xolt.freecam.util.FreeCamera$1.<init>(FreeCamera.java:25) ~[freecam-fabric-modrinth-1.2.1+1.20.jar:?]
	at net.xolt.freecam.util.FreeCamera.<clinit>(FreeCamera.java:25) ~[freecam-fabric-modrinth-1.2.1+1.20.jar:?]
	at net.xolt.freecam.Freecam.onEnableFreecam(Freecam.java:185) ~[freecam-fabric-modrinth-1.2.1+1.20.jar:?]
	at net.xolt.freecam.Freecam.toggle(Freecam.java:94) ~[freecam-fabric-modrinth-1.2.1+1.20.jar:?]
	at net.xolt.freecam.Freecam.lambda$onInitializeClient$0(Freecam.java:71) ~[freecam-fabric-modrinth-1.2.1+1.20.jar:?]
	at net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43) ~[fabric-lifecycle-events-v1-2.2.2+3bafade3a0-a9c7ef69a6eaa191.jar:?]
	at net.minecraft.class_310.handler$zho000$fabric-lifecycle-events-v1$onEndTick(class_310.java:5106) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:2007) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1237) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:856) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:253) ~[fabric-loader-0.14.22-1.20.2.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
```

**Comment by TheRubyGames** [comment]
I just wanna add I have the same problem so the creator knows it's not just you

**Comment by devjta** [comment]
I can make a 1.20.2 version..

**Comment by raoel** [comment]
https://github.com/hashalite/Freecam/pull/108 there's a download here!

**Comment by devjta** [comment]
Nice. He made the same changes I did.. Even without looking at his code. :D
