### ISSUE TITLE
Forge dev-env runs broken in 1.20.4

### ISSUE THREAD

**Issue by MattSturgeon** [hashalite/Freecam#135]
Forge (development) runs now fail with a `ResolutionException`; essentially two (identical) modules are providing the same packages, so forge panics.

Example error (from another project with the same issue as I'm not currently at a PC):

```
<==Exception in thread "main" java.lang.reflect.InvocationTargetException
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:568)
        at net.minecraftforge.bootstrap.Bootstrap.start(Bootstrap.java:48)
        at net.minecraftforge.bootstrap.ForgeBootstrap.main(ForgeBootstrap.java:18)
        at net.fabricmc.devlaunchinjector.Main.main(Main.java:86)
        at dev.architectury.transformer.TransformerRuntime.main(TransformerRuntime.java:219)
Caused by: java.lang.module.ResolutionException: Modules generated_81acd6d and animal.feeding.trough._1._20._4.dev export package slexom.animal_feeding_trough.platform.common.block.entity to module animal_feeding_trough
```

See [this thread](https://discord.com/channels/792699517631594506/1183085737940361356/1183085737940361356) on the Architectury discord.

One proposed workaround (others reported success, I've not yet tested) is removing `runtimeClasspath.extendsFrom common`.

_I guess_ both `runtimeClasspath` **and** `developmentForge` extend from `common`, so the classes are loaded twice at runtime.  
If so, I'm surprised more people aren't reporting this issue.

Opening this to keep track of the issue until I have time to put together a PR.

**Comment by hashalite** [comment]
I've just tested removing `runtimeClasspath.extendsFrom common` with no luck. There might be something configured differently on our end.
