### ISSUE TITLE
[Crash] Minecraft crashes when enabling Freecam while on fire or in lava

### ISSUE THREAD

**Issue by narutoDev** [hashalite/Freecam#61]
Minecraft 1.16.5 with only Freecam and Fabric API installed. Latest version of both.

```
[Render thread/FATAL]: Unreported exception thrown!
java.lang.NullPointerException: Cannot invoke "it.unimi.dsi.fastutil.ints.IntArrayList.getInt(int)" because "this.wrapped" is null
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$MapIterator.nextEntry(Int2ObjectOpenHashMap.java:668) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$EntryIterator.next(Int2ObjectOpenHashMap.java:742) ~[fastutil-8.2.1.jar:?]
	at it.unimi.dsi.fastutil.ints.Int2ObjectOpenHashMap$EntryIterator.next(Int2ObjectOpenHashMap.java:738) ~[fastutil-8.2.1.jar:?]
	at net.minecraft.class_638.method_18116(class_638.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1556) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1021) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:681) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:215) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.14.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.14.11.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by hashalite** [comment]
Thanks for reporting, this will be fixed in the next update (1.1.8)
